### PR TITLE
Adapt to new EcoBase.AbstractPlaces

### PR DESCRIPTION
**Pull request by mkborregaard**
@richardreeve with this, SpatialEcology works with your new implementation in EcoBase. I'll merge now, feel free to push a release of EcoBase, Diversity and SpatialEcology when ready

### CODE REVIEW

**Comment by mkborregaard** [comment]
I also did some cleanup in EcoBase

**Comment by richardreeve** [comment]
Thanks, @mkborregaard. I'm afraid I was being a bit optimistic about doing this by last weekend - I have not forgotten it though, honestly...

**Comment by richardreeve** [comment]
Okay, I've finished the other stuff I was doing and have a working branch of Diversity with the new EcoBase. Shall I release EcoBase v0.0.5 now?

**Comment by mkborregaard** [comment]
Yup sounds good

**Comment by richardreeve** [comment]
Okay, done.

**Comment by mkborregaard** [comment]
Great, I've tagged spatialecology as well

**Pull request merged**
